### ISSUE TITLE
Unable to build android

### ISSUE THREAD

**Issue by IgorGanapolsky** [touchlab/KotlinMultiplatformStarter#1]
Hello,
I opened this repo in Android Studio, and here's what I got:
<img width="1437" alt="Screen Shot 2019-08-20 at 5 26 49 PM" src="https://user-images.githubusercontent.com/201209/63385895-d4c55880-c36f-11e9-868f-072e7e5119d4.png">

Please advise,
Igor

**Comment by kpgalligan** [comment]
What version of studio? I got that on the latest canary build, but not the release build.

**Comment by IgorGanapolsky** [comment]
Latest Canary build, Kevin.

**Comment by kpgalligan** [comment]
Don't use the Canary build. There's clearly a bug in that pipeline that doesn't exist in stable builds, outside of the Kotlin gradle plugins or our code. If that persists as "Canary" approaches production, we'll look into it, but it definitely seems like something with Android Studio.

**Comment by saket** [comment]
This is being tracked here: https://issuetracker.google.com/issues/139371048
